### ISSUE TITLE
[BUG] No user agents

### ISSUE THREAD

**Issue by ak0der1** [DeBos99/adfly-bot#1]
I am getting an error 'Namespace' object has no attribute 'user_agent' 

python main.py --url http://evassmat.com/DEJJ
Executed command.

Traceback (most recent call last):
  File "main.py", line 44, in bot
    user_agent=choice(user_agents) if args.user_agent else user_agents.random
AttributeError: 'Namespace' object has no attribute 'user_agent'
(Logs of executed command.)

**Software**
OS: Mac
Python version: 3.7
WebDriver: chrome

**Comment by DeBos99** [comment]
I fixed the issue.
