### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rutakou** [DeBos99/adfly-bot#6]
I try to put after -p in cmd my local proxies list but i can't use that because there is an error in lines 66 and 78. I tried to put, after the command -p in cmd, the same link (https://www.proxy-list.download/api/v1/get?type=http&anon=elite) but again the same error in that lines.
Your project is so important for me!

**Comment by DeBos99** [comment]
Send me full logs starting with command, ending with error.

**Comment by Rutakou** [comment]
Sorry, I made a mistake! Continue with your job <3
